# Generated by Django 3.2.9 on 2021-12-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='Name',
            new_name='name',
        ),
    ]
